services:
  mssql-server-linux:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server-linux
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "LjW*i@3F"
    volumes:
      - ./data:/var/opt/mssql/data
    ports:
      - "1433:1433"
